# --- Configuración de Build ---
# Para un sitio estático puro, no se necesita un comando de build.
# Netlify simplemente desplegará los archivos del directorio raíz.
[build]
  publish = "."
  command = "echo 'PWA Estática. No se necesita build.'"

[build.environment]
  NODE_VERSION = "18"

# --- Cabeceras de Seguridad y Rendimiento ---
[[headers]]
  for = "/*" # Aplica a todas las rutas
  [headers.values]
    # Política de Seguridad de Contenido (CSP)
    # Permite contenido de 'self' y de los CDNs específicos que usamos.
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: https:;"
    
    # Previene clickjacking.
    X-Frame-Options = "DENY"
    
    # Activa el filtro XSS en navegadores.
    X-XSS-Protection = "1; mode=block"
    
    # Evita que el navegador adivine el tipo MIME.
    X-Content-Type-Options = "nosniff"
    
    # Controla la información de referer.
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Fuerza el uso de HTTPS.
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"