[build]
  publish = "."
  command = "echo 'Static site ready'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/el-borracho.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment; filename=el-borracho.apk"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/app"
  to = "/descargar.html"
  status = 301

[[redirects]]
  from = "/download"
  to = "/descargar.html"
  status = 301

[[redirects]]
  from = "/apk"
  to = "/el-borracho.apk"
  status = 301