name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Copy web assets
      run: |
        mkdir -p www
        cp -r css js images *.html *.json *.js www/
        
    - name: Sync Capacitor
      run: npx cap sync
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: el-borracho-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          🚀 Nueva versión de El Borracho disponible para Android!
          
          📱 Descargar APK directamente desde los assets de esta release.
          
          ## Cambios:
          - APK generado automáticamente desde el código fuente
          - Compatible con Android 5.0+
          - Instalación directa sin Google Play Store
          
        files: |
          android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}