name: Main CI

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install dependencies
      run: |
        npm install
        npm install -g @capacitor/cli
        npm install -g netlify-cli
        
    - name: Sync web assets with Capacitor
      run: npx cap sync android
        
    - name: '[Debug] List contents of www directory'
      run: ls -la www/

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Clean Gradle project
      run: |
        cd android
        ./gradlew clean

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon --stacktrace --info

    - name: '[Debug] List contents of APK output directory'
      run: ls -la android/app/build/outputs/apk/debug/

    - name: Deploy to Netlify
      run: |
        netlify deploy --prod --dir . --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: el-borracho-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create Release (only on main branch)
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: "El Borracho v${{ github.run_number }}"
        body: |
          🚀 **Nueva versión de El Borracho disponible!**
          
          📱 **Para Android:**
          - Descarga el archivo `app-debug.apk` desde los assets
          - Instala directamente en tu dispositivo Android
          - Compatible con Android 5.0+
          
          ## ✨ Características:
          - Sistema de pedidos profesional con códigos únicos
          - Doble WhatsApp (cliente + domicilios)
          - Seguimiento de pedidos en tiempo real
          - Checkout completo con validación
          - Instalación sin Google Play Store
          
          ## 📥 Instalación:
          1. Descarga `app-debug.apk`
          2. Habilita "Fuentes desconocidas" en Android
          3. Instala el APK
          4. ¡Disfruta pidiendo licores a domicilio!
          
        files: android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
